-- The :Msvc user command is created by `require("msvc").setup({...})`.
-- This file is intentionally empty so the plugin does nothing until the
-- user calls setup, matching harpoon2's lazy-init style.
