local TestUtils = require("msvc.test.utils")

describe("MsvcLog", function()
    before_each(function()
        TestUtils.reset()
    end)

    it("rings to max_lines", function()
        local Log = require("msvc.log")
        Log.max_lines = 5
        Log:clear()
        local cap = TestUtils.capture_notify()
        for i = 1, 12 do
            Log:info("msg-%d", i)
        end
        cap.restore()
        assert.equals(5, #Log.lines)
        assert.is_true(Log.lines[1]:find("msg-8", 1, true) ~= nil)
        assert.is_true(Log.lines[5]:find("msg-12", 1, true) ~= nil)
    end)

    it("respects level threshold", function()
        local Log = require("msvc.log")
        Log:clear()
        Log:set_level("warn")
        local cap = TestUtils.capture_notify()
        Log:debug("d")
        Log:info("i")
        Log:warn("w")
        Log:error("e")
        cap.restore()
        assert.equals(2, #cap.calls)
        assert.equals(vim.log.levels.WARN, cap.calls[1].level)
        assert.equals(vim.log.levels.ERROR, cap.calls[2].level)
    end)

    it("can be disabled", function()
        local Log = require("msvc.log")
        Log:clear()
        Log:set_level("debug")
        Log:disable()
        local cap = TestUtils.capture_notify()
        Log:error("nope")
        cap.restore()
        assert.equals(0, #cap.calls)
        assert.equals(0, #Log.lines)
        Log:enable()
    end)

    it("rejects unknown level names", function()
        local Log = require("msvc.log")
        assert.has_error(function()
            Log:set_level("loud")
        end)
    end)
end)
